name: github-action

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.6.5', '9.4.8', '9.6.3', '9.8.1']
        os: ['ubuntu-latest']
        include:
        - ghc: '9.8.1'
          os:  'macos-latest'
        - ghc: '9.8.1'
          os:  'windows-latest'

    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test --enable-tests all
    - name: Build Docs
      run: cabal haddock
